version: '3.8'
services:
  user:
    build: ./microservices/user
    ports:
      - "8001:8000"

  payment:
    build: ./microservices/payment
    ports:
      - "8002:8000"

  frontend:
    build: ./microservices/frontend
    ports:
      - "8080:80"

  dashboard:
    build: ./microservices/dashboard
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # share code for easy updates