name: AppSec Demo - Automation Gate

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: docker compose build

      - name: Dependency scan (pip-audit on Python services)
        run: |
          pip install pip-audit
          pip-audit -r microservices/user/requirements.txt || true
          pip-audit -r microservices/payment/requirements.txt || true

      - name: Lint all Dockerfiles (hadolint)
        run: |
          docker run --rm -v $(pwd):/workdir hadolint/hadolint \
                  hadolint /workdir/microservices/user/Dockerfile \
                           /workdir/microservices/payment/Dockerfile \
                           /workdir/microservices/frontend/Dockerfile || true
       #       continue-on-error: true  # optional: keeps job going even if warnings
                    

    #  - name: Dockerfile lint (hadolint)
    #   uses: hadolint/hadolint-action@v3.1.0
    #    with:
    #      dockerfile: |
    #        microservices/user/Dockerfile
    #        microservices/payment/Dockerfile
    #        microservices/frontend/Dockerfile
    #      failure-threshold: warning

